//! Styled, self-contained, print-ready HTML findings report.
//!
//! Renders a deterministic HTML report from a slice of [`Finding`]s. Every
//! finding field that originates from scanned repository content (title,
//! description, location, recommendation, CWE ids, OWASP category, scanner name,
//! and corroboration list) is HTML-escaped before it reaches the page. The
//! output carries all CSS inline and includes `@page` and `@media print`
//! rules so the report prints cleanly as a white-paper PDF without external
//! assets.

use crate::config::{cwe_link, DEFAULT_CWE_URL_TEMPLATE};
use crate::state::finding::{Finding, Screening, Severity};

/// Render a self-contained HTML security report from findings.
///
/// The output is deterministic: findings are sorted by severity, then location,
/// then title, then scanner. The page uses a default executive title of
/// "Zentra SAST Report". Use [`render_report_html`] when you need to add
/// project, branch, CI scope, or other metadata lines.
pub fn render_findings_html(findings: &[Finding]) -> String {
    render_report_html(findings, "Zentra SAST Report", &[])
}

/// Render a self-contained HTML report with a custom title and header metadata.
///
/// `meta` is a list of `(label, value)` pairs shown in the executive header.
/// Values are HTML-escaped. The report is deterministic for the same inputs.
pub fn render_report_html(findings: &[Finding], title: &str, meta: &[(&str, &str)]) -> String {
    let sorted = sorted_findings(findings);
    let counts = severity_counts(findings);
    let total = findings.len();

    let meta_html = meta
        .iter()
        .map(|(label, value)| {
            format!(
                "<div class=\"meta-item\"><span class=\"meta-label\">{}</span><span class=\"meta-value\">{}</span></div>",
                escape_html(label),
                escape_html(value)
            )
        })
        .collect::<String>();
    let meta_html = if meta_html.is_empty() {
        meta_html
    } else {
        format!(r#"<div class="meta-grid">{}</div>"#, meta_html)
    };

    let severity_summary = render_severity_summary(&counts, total);
    let findings_html = if sorted.is_empty() {
        render_empty_state()
    } else {
        sorted
            .iter()
            .map(|f| render_finding_card(f))
            .collect::<String>()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{}</title>
<style>
{}
</style>
</head>
<body>
<header class="exec-header">
  <div class="brand">Zentra</div>
  <h1>{}</h1>
  {}
  {}
</header>
<main>
  <section class="findings" aria-label="Findings">
    {}
  </section>
</main>
<footer class="report-footer">
  Generated by Zentra {}
</footer>
</body>
</html>"#,
        escape_html(title),
        CSS,
        escape_html(title),
        meta_html,
        severity_summary,
        findings_html,
        env!("CARGO_PKG_VERSION"),
    )
}

/// Sort findings deterministically: severity, location, title, scanner.
fn sorted_findings(findings: &[Finding]) -> Vec<&Finding> {
    let mut sorted: Vec<&Finding> = findings.iter().collect();
    sorted.sort_by(|a, b| {
        a.severity
            .order()
            .cmp(&b.severity.order())
            .then_with(|| {
                a.location
                    .as_deref()
                    .unwrap_or("")
                    .cmp(b.location.as_deref().unwrap_or(""))
            })
            .then_with(|| a.title.cmp(&b.title))
            .then_with(|| a.scanner.cmp(&b.scanner))
    });
    sorted
}

fn severity_counts(findings: &[Finding]) -> [usize; 5] {
    let mut counts = [0usize; 5];
    for finding in findings {
        counts[finding.severity.order() as usize] += 1;
    }
    counts
}

fn render_severity_summary(counts: &[usize; 5], total: usize) -> String {
    let ordered = [
        (Severity::Critical, "Critical", "critical"),
        (Severity::High, "High", "high"),
        (Severity::Medium, "Medium", "medium"),
        (Severity::Low, "Low", "low"),
        (Severity::Info, "Info", "info"),
    ];

    let cards = ordered
        .iter()
        .enumerate()
        .map(|(idx, (_sev, label, class))| {
            let count = counts[idx];
            format!(
                r#"<div class="severity-card {class}">
  <div class="severity-count-cell">{count}</div>
  <div class="severity-label-cell">{label}</div>
</div>"#
            )
        })
        .collect::<String>();

    format!(
        r#"<div class="severity-summary">
  <div class="total-card">
    <div class="severity-count-cell">{total}</div>
    <div class="severity-label-cell">Total findings</div>
  </div>
  {cards}
</div>"#
    )
}

fn render_empty_state() -> String {
    r#"<div class="empty-state">
  <div class="empty-icon">✓</div>
  <h2>No findings detected</h2>
  <p>The scan completed without identifying any security issues in scope.</p>
</div>"#
        .to_string()
}

fn render_finding_card(finding: &Finding) -> String {
    let severity_class = severity_css_class(finding.severity);
    let severity_label = escape_html(&finding.severity.to_string());
    let title = escape_html(&finding.title);
    let scanner = escape_html(&finding.scanner);

    let location = finding
        .location
        .as_deref()
        .filter(|l| !l.is_empty())
        .map(|l| render_field("Location", &format!("<code>{}</code>", escape_html(l))))
        .unwrap_or_default();

    let description = render_field("Description", &paragraphs(&finding.description));
    let recommendation = render_field("Recommendation", &paragraphs(&finding.recommendation));

    let cwe = finding.cwe.as_deref().map(|id| {
        let trimmed = id.trim();
        let url = cwe_link(trimmed, DEFAULT_CWE_URL_TEMPLATE);
        render_field(
            "CWE",
            &format!(
                r#"<a href="{}" target="_blank" rel="noopener noreferrer">{}</a>"#,
                escape_html(&url),
                escape_html(trimmed)
            ),
        )
    });

    let secondary_cwe = if finding.secondary_cwe.is_empty() {
        None
    } else {
        let links: Vec<String> = finding
            .secondary_cwe
            .iter()
            .map(|id| {
                let trimmed = id.trim();
                let url = cwe_link(trimmed, DEFAULT_CWE_URL_TEMPLATE);
                format!(
                    r#"<a href="{}" target="_blank" rel="noopener noreferrer">{}</a>"#,
                    escape_html(&url),
                    escape_html(trimmed)
                )
            })
            .collect();
        Some(render_field("Secondary CWE", &links.join(", ")))
    };

    let cvss = match (finding.cvss_score, finding.cvss_vector.as_deref()) {
        (Some(score), Some(vector)) => Some(render_field(
            "CVSS",
            &format!(
                "<span class=\"cvss-score\">{:.1}</span> <span class=\"cvss-rating\">{}</span> <span class=\"cvss-vector\">{}</span>",
                score,
                escape_html(crate::state::cvss::rating(score)),
                escape_html(vector)
            ),
        )),
        _ => None,
    };

    let owasp = finding.owasp.as_deref().filter(|o| !o.is_empty()).map(|o| {
        render_field(
            "OWASP",
            &format!("<span class=\"tag\">{}</span>", escape_html(o)),
        )
    });

    let corroboration = if finding.corroborated_by.is_empty() {
        None
    } else {
        let tags: Vec<String> = finding
            .corroborated_by
            .iter()
            .map(|s| {
                format!(
                    "<span class=\"tag corroboration-tag\">{}</span>",
                    escape_html(s)
                )
            })
            .collect();
        Some(render_field("Corroborated by", &tags.join(" ")))
    };

    let screening = match (finding.screening, finding.confidence) {
        (Some(verdict), Some(confidence)) => Some(format!(
            r#"<div class="screening-badge screening-{}">{} <span class="confidence">({}% confidence)</span></div>"#,
            screening_css_class(verdict),
            escape_html(&verdict.to_string()),
            confidence
        )),
        (Some(verdict), None) => Some(format!(
            r#"<div class="screening-badge screening-{}">{}</div>"#,
            screening_css_class(verdict),
            escape_html(&verdict.to_string())
        )),
        _ => None,
    };

    let details = [
        location,
        cwe.unwrap_or_default(),
        secondary_cwe.unwrap_or_default(),
        cvss.unwrap_or_default(),
        owasp.unwrap_or_default(),
        corroboration.unwrap_or_default(),
        description,
        recommendation,
    ]
    .concat();

    format!(
        r#"<article class="finding-card {severity_class}">
  <div class="card-header">
    <div class="card-title-row">
      <span class="severity-badge">{severity_label}</span>
      <h2>{title}</h2>
    </div>
    <div class="card-subtitle">
      <span class="scanner-badge">{scanner}</span>
      {screening}
    </div>
  </div>
  <div class="card-body">
    {details}
  </div>
</article>"#,
        screening = screening.unwrap_or_default()
    )
}

fn render_field(label: &str, value_html: &str) -> String {
    format!(
        r#"<div class="field">
  <div class="field-label">{}</div>
  <div class="field-value">{}</div>
</div>"#,
        escape_html(label),
        value_html
    )
}

/// Convert plain text with line breaks into `<p>` paragraphs, escaping first.
fn paragraphs(text: &str) -> String {
    text.split('\n')
        .filter(|line| !line.is_empty())
        .map(|line| format!("<p>{}</p>", escape_html(line)))
        .collect::<String>()
}

fn severity_css_class(severity: Severity) -> &'static str {
    match severity {
        Severity::Critical => "severity-critical",
        Severity::High => "severity-high",
        Severity::Medium => "severity-medium",
        Severity::Low => "severity-low",
        Severity::Info => "severity-info",
    }
}

fn screening_css_class(screening: Screening) -> &'static str {
    match screening {
        Screening::Confirmed => "confirmed",
        Screening::Disputed => "disputed",
        Screening::Unclear => "unclear",
    }
}

/// Escape a value so it is safe to embed in HTML text or attribute contexts.
fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(ch),
        }
    }
    out
}

const CSS: &str = r#"
:root {
  /* Neutral/slate light document with a modest dark executive cover band. */
  --background: #f8fafc;       /* slate-50 */
  --background-subtle: #f1f5f9; /* slate-100 */
  --layer: #ffffff;
  --layer-hover: #f8fafc;
  --text-primary: #0f172a;       /* slate-900 */
  --text-secondary: #475569;     /* slate-600 */
  --text-placeholder: #94a3b8;   /* slate-400 */
  --text-inverse: #ffffff;
  --link-primary: #0f766e;       /* teal-700: restrained non-Ory accent */
  --link-primary-hover: #115e59; /* teal-800 */
  --border-subtle: #e2e8f0;      /* slate-200 */
  --border-strong: #94a3b8;      /* slate-400 */
  --border-inverse: #0f172a;

  /* Severity/status tokens: solid, accessible colors for header/cell areas. */
  --critical: #991b1b;           /* red-800 */
  --high: #c2410c;               /* orange-700 */
  --medium: #a16207;             /* yellow-700 */
  --low: #1d4ed8;                /* blue-700 */
  --info: #334155;               /* slate-700 */
  --critical-light: #fee2e2;
  --high-light: #ffedd5;
  --medium-light: #fef3c7;
  --low-light: #dbeafe;
  --info-light: #f1f5f9;
  --confirmed: #15803d;
  --disputed: #991b1b;
  --unclear: #a16207;

  /* Spacing: generous whitespace. */
  --space-01: 2px;
  --space-02: 4px;
  --space-03: 8px;
  --space-04: 12px;
  --space-05: 16px;
  --space-06: 24px;
  --space-07: 32px;
  --space-08: 40px;
  --space-09: 48px;
  --space-10: 64px;
  --space-11: 80px;

  /* Typography: Inter + JetBrains-compatible fallbacks. */
  --font-sans: "Inter", "Helvetica Neue", Arial, "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
  --font-mono: "JetBrains Mono", "Menlo", "DejaVu Sans Mono", "Consolas", "Liberation Mono", monospace;

  /* Layout */
  --max-content-width: 1056px;
  --radius-sm: 2px;
  --radius-md: 4px;
  --radius-lg: 8px;
}

@page {
  size: auto;
  margin: 20mm 18mm 24mm 18mm;
}

* {
  box-sizing: border-box;
}

html {
  font-size: 100%;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  margin: 0;
  padding: 0;
  background: var(--background);
  color: var(--text-primary);
  font-family: var(--font-sans);
  font-size: 16px;
  line-height: 1.55;
  letter-spacing: 0.01em;
}

h1, h2, h3, h4, h5, h6, p {
  margin: 0;
}

a {
  color: var(--link-primary);
  text-decoration: none;
  border-bottom: 1px solid transparent;
  transition: border-bottom-color 0.15s ease, color 0.15s ease;
}

a:hover {
  color: var(--link-primary-hover);
  border-bottom-color: var(--link-primary-hover);
}

code {
  font-family: var(--font-mono);
  font-size: 0.875em;
}

.exec-header {
  max-width: var(--max-content-width);
  margin: 0 auto;
  padding: var(--space-10) var(--space-08) var(--space-08);
  background: #0f172a; /* modest dark executive cover band */
  color: #f8fafc;
  border-bottom: 1px solid #1e293b;
}

.brand {
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: #5eead4; /* restrained teal accent on dark band */
  margin-bottom: var(--space-04);
}

.exec-header h1 {
  font-size: clamp(2rem, 5vw, 3rem);
  font-weight: 500;
  line-height: 1.15;
  margin-bottom: var(--space-07);
  color: #f8fafc;
}

.meta-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: var(--space-06);
}

.meta-item {
  display: flex;
  flex-direction: column;
  gap: var(--space-02);
}

.meta-label {
  font-size: 0.6875rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  color: #94a3b8;
  text-transform: uppercase;
}

.meta-value {
  font-size: 0.9375rem;
  color: #f1f5f9;
  line-height: 1.4;
  word-break: break-word;
}

.severity-summary {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-04);
}

.total-card,
.severity-card {
  flex: 1 1 120px;
  min-width: 120px;
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-md);
  overflow: hidden;
  background: var(--layer);
}

.severity-count-cell {
  padding: var(--space-05) var(--space-05) var(--space-04);
  font-size: 1.75rem;
  font-weight: 700;
  line-height: 1.2;
  color: var(--text-inverse);
  text-align: center;
  background: var(--info);
}

.severity-label-cell {
  padding: var(--space-03) var(--space-05);
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  text-align: center;
  color: var(--text-secondary);
  background: var(--background);
  border-top: 1px solid var(--border-subtle);
}

.total-card .severity-count-cell {
  background: var(--text-primary);
}

.severity-card.critical .severity-count-cell { background: var(--critical); }
.severity-card.high .severity-count-cell { background: var(--high); }
.severity-card.medium .severity-count-cell { background: var(--medium); }
.severity-card.low .severity-count-cell { background: var(--low); }
.severity-card.info .severity-count-cell { background: var(--info); }

.findings {
  max-width: var(--max-content-width);
  margin: 0 auto;
  padding: var(--space-08);
  display: flex;
  flex-direction: column;
  gap: var(--space-07);
  background: var(--layer);
}

.finding-card {
  background: var(--layer);
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-md);
  overflow: hidden;
}

.card-header {
  padding: var(--space-06) var(--space-07);
  border-bottom: 1px solid var(--border-subtle);
  background: var(--layer-hover);
}

.finding-card.severity-critical .card-header { background: var(--critical); color: var(--text-inverse); }
.finding-card.severity-high .card-header { background: var(--high); color: var(--text-inverse); }
.finding-card.severity-medium .card-header { background: var(--medium); color: var(--text-inverse); }
.finding-card.severity-low .card-header { background: var(--low); color: var(--text-inverse); }
.finding-card.severity-info .card-header { background: var(--info); color: var(--text-inverse); }

.card-title-row {
  display: flex;
  align-items: flex-start;
  gap: var(--space-04);
  flex-wrap: wrap;
}

.card-title-row h2 {
  font-size: 1.25rem;
  font-weight: 600;
  line-height: 1.3;
  color: inherit;
}

.severity-badge {
  display: inline-flex;
  align-items: center;
  padding: var(--space-02) var(--space-03);
  border-radius: var(--radius-md);
  font-size: 0.6875rem;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  white-space: nowrap;
  background: rgba(255, 255, 255, 0.18);
  color: inherit;
  border: 1px solid rgba(255, 255, 255, 0.35);
}

.card-subtitle {
  display: flex;
  align-items: center;
  gap: var(--space-04);
  flex-wrap: wrap;
  margin-top: var(--space-04);
}

.scanner-badge {
  font-size: 0.75rem;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: inherit;
  opacity: 0.9;
}

.screening-badge {
  display: inline-flex;
  align-items: center;
  gap: var(--space-02);
  padding: var(--space-02) var(--space-03);
  border-radius: var(--radius-md);
  font-size: 0.6875rem;
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  background: rgba(255, 255, 255, 0.12);
  border: 1px solid rgba(255, 255, 255, 0.35);
  color: inherit;
}

.screening-badge.confirmed { background: rgba(21, 128, 61, 0.18); border-color: rgba(21, 128, 61, 0.45); }
.screening-badge.disputed { background: rgba(153, 27, 27, 0.18); border-color: rgba(153, 27, 27, 0.45); }
.screening-badge.unclear { background: rgba(161, 98, 7, 0.18); border-color: rgba(161, 98, 7, 0.45); }

.screening-badge .confidence {
  font-weight: 500;
  text-transform: none;
  letter-spacing: 0;
  opacity: 0.85;
}

.card-body {
  padding: var(--space-07);
  display: flex;
  flex-direction: column;
  gap: var(--space-05);
}

.field {
  display: flex;
  flex-direction: column;
  gap: var(--space-02);
}

.field-label {
  font-size: 0.6875rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  color: var(--text-secondary);
  text-transform: uppercase;
}

.field-value {
  font-size: 0.9375rem;
  line-height: 1.55;
  color: var(--text-primary);
}

.field-value p {
  margin: 0 0 var(--space-03) 0;
}

.field-value p:last-child {
  margin-bottom: 0;
}

.field-value code {
  background: var(--background-subtle);
  color: var(--text-primary);
  padding: var(--space-01) var(--space-02);
  border-radius: var(--radius-sm);
  border: 1px solid var(--border-subtle);
}

.tag {
  display: inline-flex;
  align-items: center;
  padding: var(--space-02) var(--space-03);
  border-radius: var(--radius-md);
  font-size: 0.75rem;
  font-weight: 600;
  background: var(--background-subtle);
  border: 1px solid var(--border-subtle);
  color: var(--text-primary);
  margin: 0 var(--space-02) var(--space-02) 0;
}

.corroboration-tag {
  background: #dcfce7;
  border-color: #15803d;
  color: #14532d;
}

.cvss-score {
  font-size: 1rem;
  font-weight: 600;
  color: var(--text-primary);
}

.cvss-rating {
  font-weight: 600;
  color: var(--text-secondary);
}

.cvss-vector {
  font-family: var(--font-mono);
  font-size: 0.875em;
  color: var(--text-secondary);
  word-break: break-word;
}

.empty-state {
  text-align: center;
  padding: var(--space-10);
  background: var(--layer);
  border: 1px solid var(--border-subtle);
  border-radius: var(--radius-md);
}

.empty-icon {
  width: var(--space-08);
  height: var(--space-08);
  margin: 0 auto var(--space-05);
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: #dcfce7;
  color: var(--confirmed);
  font-size: 1.5rem;
  font-weight: 600;
}

.empty-state h2 {
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: var(--space-03);
  color: var(--text-primary);
}

.empty-state p {
  font-size: 0.9375rem;
  color: var(--text-secondary);
}

.report-footer {
  max-width: var(--max-content-width);
  margin: 0 auto;
  padding: var(--space-05) var(--space-08);
  text-align: center;
  font-size: 0.75rem;
  color: var(--text-secondary);
  border-top: 1px solid var(--border-subtle);
  background: var(--layer);
}

/* Screen enhancements: subtle paper-on-slate-gray presentation. */
@media screen {
  body {
    background: var(--background-subtle);
  }

  .exec-header,
  .findings,
  .report-footer {
    border-left: 1px solid var(--border-subtle);
    border-right: 1px solid var(--border-subtle);
  }

  .exec-header {
    margin-top: var(--space-06);
    border-top: 1px solid var(--border-subtle);
    border-radius: var(--radius-md) var(--radius-md) 0 0;
  }

  .report-footer {
    margin-bottom: var(--space-06);
    border-bottom: 1px solid var(--border-subtle);
    border-radius: 0 0 var(--radius-md) var(--radius-md);
  }
}

/* Print-first refinements: white paper, readable type, no card splits, printed URLs. */
@media print {
  :root {
    --background: #ffffff;
    --layer: #ffffff;
    --layer-hover: #f4f4f4;
    --text-primary: #0f172a;
    --text-secondary: #475569;
  }

  body {
    background: #ffffff;
    color: #0f172a;
    font-size: 11pt;
    line-height: 1.45;
  }

  .exec-header,
  .findings,
  .report-footer {
    max-width: none;
    margin: 0;
    padding-left: 0;
    padding-right: 0;
    background: #ffffff;
    border: none;
    border-radius: 0;
    color: #0f172a;
  }

  .exec-header {
    margin-top: 0;
    padding-top: 0;
    background: #0f172a;
    color: #f8fafc;
  }

  .exec-header h1,
  .exec-header .brand,
  .exec-header .meta-value,
  .exec-header .meta-label {
    color: #f8fafc;
  }

  .report-footer {
    margin-bottom: 0;
  }

  .finding-card,
  .severity-card,
  .total-card,
  .empty-state {
    background: #ffffff;
    break-inside: avoid;
    page-break-inside: avoid;
  }

  .finding-card {
    border: 1px solid #94a3b8;
  }

  .finding-card.severity-critical .card-header { background: var(--critical); color: #ffffff; }
  .finding-card.severity-high .card-header { background: var(--high); color: #ffffff; }
  .finding-card.severity-medium .card-header { background: var(--medium); color: #ffffff; }
  .finding-card.severity-low .card-header { background: var(--low); color: #ffffff; }
  .finding-card.severity-info .card-header { background: var(--info); color: #ffffff; }

  .severity-count-cell,
  .card-header,
  .severity-badge,
  .screening-badge,
  .tag {
    print-color-adjust: exact;
    -webkit-print-color-adjust: exact;
  }

  a {
    color: #0f172a;
    text-decoration: none;
    border-bottom: 1px solid #94a3b8;
  }

  a[href^="http"]::after,
  a[href^="https"]::after {
    content: " (" attr(href) ")";
    font-size: 0.85em;
    color: #475569;
    word-break: break-all;
    border-bottom: none;
  }

  .card-header {
    background: #f1f5f9;
  }

  .finding-card.severity-critical .card-header,
  .finding-card.severity-high .card-header,
  .finding-card.severity-medium .card-header,
  .finding-card.severity-low .card-header,
  .finding-card.severity-info .card-header {
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }

  .corroboration-tag {
    background: #f1f5f9;
    border-color: #94a3b8;
    color: #0f172a;
  }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::finding::{Finding, Screening, Severity};

    fn sample_finding() -> Finding {
        Finding {
            scanner: "sast".to_string(),
            severity: Severity::High,
            title: "SQL Injection".to_string(),
            description: "User input concatenated into query.\nSecond line.".to_string(),
            location: Some("src/db.rs:42".to_string()),
            recommendation: "Use parameterized queries".to_string(),
            corroborated_by: vec!["supply-chain".to_string()],
            cwe: Some("CWE-89".to_string()),
            secondary_cwe: vec!["CWE-20".to_string()],
            cvss_vector: Some("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H".to_string()),
            cvss_score: Some(9.8),
            owasp: Some("A03:2021-Injection".to_string()),
            confidence: Some(85),
            screening: Some(Screening::Confirmed),
            evidence: None,
        }
    }

    #[test]
    fn empty_findings_render_valid_html() {
        let html = render_findings_html(&[]);
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("No findings detected"));
        assert!(html.contains("Total findings"));
    }

    #[test]
    fn rendering_is_deterministic() {
        let findings = vec![sample_finding()];
        let a = render_findings_html(&findings);
        let b = render_findings_html(&findings);
        assert_eq!(a, b, "same findings must produce byte-identical HTML");
    }

    #[test]
    fn untrusted_fields_are_escaped() {
        let mut f = sample_finding();
        f.title = "<img src=x onerror=alert(1)>".to_string();
        f.description = "<script>alert(1)</script>".to_string();
        f.location = Some("src/<foo>.rs:1".to_string());
        f.scanner = "scanner&co".to_string();
        f.cwe = Some("CWE-89\"".to_string());
        f.owasp = Some("A01'x".to_string());

        let html = render_findings_html(&[f]);
        assert!(!html.contains("<img src=x onerror=alert(1)>"));
        assert!(html.contains("&lt;img src=x onerror=alert(1)&gt;"));
        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(!html.contains("src/<foo>.rs:1"));
        assert!(html.contains("src/&lt;foo&gt;.rs:1"));
        assert!(!html.contains("scanner&co"));
        assert!(html.contains("scanner&amp;co"));
        assert!(!html.contains("CWE-89\""));
        assert!(html.contains("CWE-89&quot;"));
        assert!(html.contains("A01&#39;x"));
    }

    #[test]
    fn severity_summary_counts_are_correct() {
        let html = render_findings_html(&[sample_finding()]);
        assert!(html.contains(r#"<div class="severity-label-cell">Total findings</div>"#));
        assert!(html.contains(r#"<div class="severity-card high">"#));
        assert!(html.contains(r#"<div class="severity-label-cell">High</div>"#));
        assert!(html.contains(r#"<div class="severity-count-cell">1</div>"#));
    }

    #[test]
    fn enriched_finding_renders_fields() {
        let html = render_findings_html(&[sample_finding()]);
        assert!(html.contains("SQL Injection"));
        assert!(html.contains("src/db.rs:42"));
        assert!(html.contains("User input concatenated into query."));
        assert!(html.contains("Use parameterized queries"));
        assert!(html.contains("CWE-89"));
        assert!(html.contains("CWE-20"));
        assert!(html.contains("9.8"));
        assert!(html.contains("A03:2021-Injection"));
        assert!(html.contains("supply-chain"));
        assert!(html.contains("confirmed"));
        assert!(html.contains("85% confidence"));
    }

    #[test]
    fn cwe_link_points_at_default_template() {
        let html = render_findings_html(&[sample_finding()]);
        assert!(html.contains("https://cwe.mitre.org/data/definitions/89.html"));
        assert!(html.contains("https://cwe.mitre.org/data/definitions/20.html"));
    }

    #[test]
    fn report_meta_lines_are_escaped() {
        let html = render_report_html(
            &[],
            "Title<script>",
            &[("Key<img>", "Value&"), ("Branch", "feat/<x>")],
        );
        assert!(html.contains("Title&lt;script&gt;"));
        assert!(html.contains("Key&lt;img&gt;"));
        assert!(html.contains("Value&amp;"));
        assert!(html.contains("feat/&lt;x&gt;"));
    }

    #[test]
    fn findings_sorted_by_severity_then_location_then_title() {
        let b = Finding {
            scanner: "b".to_string(),
            severity: Severity::Critical,
            title: "B".to_string(),
            description: "d".to_string(),
            location: Some("src/b.rs:1".to_string()),
            recommendation: "r".to_string(),
            ..sample_finding()
        };
        let a = Finding {
            scanner: "a".to_string(),
            severity: Severity::Critical,
            title: "A".to_string(),
            description: "d".to_string(),
            location: Some("src/a.rs:1".to_string()),
            recommendation: "r".to_string(),
            ..sample_finding()
        };
        let html = render_findings_html(&[b.clone(), a.clone()]);
        let a_pos = html.find("<h2>A</h2>").unwrap();
        let b_pos = html.find("<h2>B</h2>").unwrap();
        assert!(a_pos < b_pos, "A must appear before B");
    }

    #[test]
    fn report_includes_slate_print_rules_and_fonts() {
        let html = render_findings_html(&[sample_finding()]);
        assert!(html.contains("@page"));
        assert!(html.contains("@media print"));
        assert!(html.contains("break-inside: avoid"));
        assert!(html.contains("Inter"));
        assert!(html.contains("JetBrains Mono"));
        assert!(html.contains("@media print"));
    }

    #[test]
    fn finding_has_severity_colored_header_not_left_edge() {
        let mut f = sample_finding();
        f.severity = Severity::Critical;
        let html = render_findings_html(&[f]);
        // No severity-colored left border edge remains.
        assert!(!html.contains("border-left: 3px"));
        assert!(!html.contains("border-left-color"));
        // Header area carries the severity background.
        assert!(html.contains(
            ".finding-card.severity-critical .card-header { background: var(--critical);"
        ));
    }

    #[test]
    fn severity_summary_count_sits_in_colored_cell() {
        let mut f = sample_finding();
        f.severity = Severity::High;
        let html = render_findings_html(&[f]);
        // Each metric count is inside a colored cell, not just a bare number or border.
        assert!(html.contains(r#"<div class="severity-count-cell">1</div>"#));
        assert!(
            html.contains(".severity-card.high .severity-count-cell { background: var(--high);")
        );
        assert!(html.contains(r#"<div class="severity-label-cell">High</div>"#));
    }

    #[test]
    fn empty_meta_does_not_emit_meta_grid() {
        let html = render_findings_html(&[]);
        assert!(!html.contains(r#"class="meta-grid""#));
    }

    #[test]
    fn non_empty_meta_wraps_in_grid() {
        let html = render_report_html(&[], "Report", &[("Project", "demo")]);
        assert!(html.contains(r#"<div class="meta-grid">"#));
        assert!(html.contains(r#"<span class="meta-label">Project</span>"#));
        assert!(html.contains(r#"<span class="meta-value">demo</span>"#));
    }
}
