//! Styled, self-contained, print-ready HTML findings report.
//!
//! Renders a deterministic HTML report from a slice of [`Finding`]s. Every
//! finding field that originates from scanned repository content (title,
//! description, location, recommendation, CWE ids, OWASP category, scanner name,
//! and corroboration list) is HTML-escaped before it reaches the page. The
//! output carries all CSS inline and includes a `@media print` rule so the
//! report prints cleanly without external assets.

use crate::config::{cwe_link, DEFAULT_CWE_URL_TEMPLATE};
use crate::state::finding::{Finding, Screening, Severity};

/// Render a self-contained HTML security report from findings.
///
/// The output is deterministic: findings are sorted by severity, then location,
/// then title, then scanner. The page uses a default executive title of
/// "Zentra SAST Report". Use [`render_report_html`] when you need to add
/// project, branch, CI scope, or other metadata lines.
pub fn render_findings_html(findings: &[Finding]) -> String {
    render_report_html(findings, "Zentra SAST Report", &[])
}

/// Render a self-contained HTML report with a custom title and header metadata.
///
/// `meta` is a list of `(label, value)` pairs shown in the executive header.
/// Values are HTML-escaped. The report is deterministic for the same inputs.
pub fn render_report_html(findings: &[Finding], title: &str, meta: &[(&str, &str)]) -> String {
    let sorted = sorted_findings(findings);
    let counts = severity_counts(findings);
    let total = findings.len();

    let meta_html = meta
        .iter()
        .map(|(label, value)| {
            format!(
                "<div class=\"meta-item\"><span class=\"meta-label\">{}</span><span class=\"meta-value\">{}</span></div>",
                escape_html(label),
                escape_html(value)
            )
        })
        .collect::<String>();

    let severity_summary = render_severity_summary(&counts, total);
    let findings_html = if sorted.is_empty() {
        render_empty_state()
    } else {
        sorted
            .iter()
            .map(|f| render_finding_card(f))
            .collect::<String>()
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{}</title>
<style>
{}
</style>
</head>
<body>
<header class="exec-header">
  <div class="brand">Zentra</div>
  <h1>{}</h1>
  {}
  {}
</header>
<main>
  <section class="findings" aria-label="Findings">
    {}
  </section>
</main>
<footer class="report-footer">
  Generated by Zentra {}
</footer>
</body>
</html>"#,
        escape_html(title),
        CSS,
        escape_html(title),
        meta_html,
        severity_summary,
        findings_html,
        env!("CARGO_PKG_VERSION"),
    )
}

/// Sort findings deterministically: severity, location, title, scanner.
fn sorted_findings(findings: &[Finding]) -> Vec<&Finding> {
    let mut sorted: Vec<&Finding> = findings.iter().collect();
    sorted.sort_by(|a, b| {
        a.severity
            .order()
            .cmp(&b.severity.order())
            .then_with(|| {
                a.location
                    .as_deref()
                    .unwrap_or("")
                    .cmp(b.location.as_deref().unwrap_or(""))
            })
            .then_with(|| a.title.cmp(&b.title))
            .then_with(|| a.scanner.cmp(&b.scanner))
    });
    sorted
}

fn severity_counts(findings: &[Finding]) -> [usize; 5] {
    let mut counts = [0usize; 5];
    for finding in findings {
        counts[finding.severity.order() as usize] += 1;
    }
    counts
}

fn render_severity_summary(counts: &[usize; 5], total: usize) -> String {
    let ordered = [
        (Severity::Critical, "Critical", "critical"),
        (Severity::High, "High", "high"),
        (Severity::Medium, "Medium", "medium"),
        (Severity::Low, "Low", "low"),
        (Severity::Info, "Info", "info"),
    ];

    let cards = ordered
        .iter()
        .enumerate()
        .map(|(idx, (_sev, label, class))| {
            let count = counts[idx];
            format!(
                r#"<div class="severity-card {class}">
  <span class="severity-count">{count}</span>
  <span class="severity-label">{label}</span>
</div>"#
            )
        })
        .collect::<String>();

    format!(
        r#"<div class="severity-summary">
  <div class="total-card">
    <span class="severity-count">{total}</span>
    <span class="severity-label">Total findings</span>
  </div>
  {cards}
</div>"#
    )
}

fn render_empty_state() -> String {
    r#"<div class="empty-state">
  <div class="empty-icon">✓</div>
  <h2>No findings detected</h2>
  <p>The scan completed without identifying any security issues in scope.</p>
</div>"#
        .to_string()
}

fn render_finding_card(finding: &Finding) -> String {
    let severity_class = severity_css_class(finding.severity);
    let severity_label = escape_html(&finding.severity.to_string());
    let title = escape_html(&finding.title);
    let scanner = escape_html(&finding.scanner);

    let location = finding
        .location
        .as_deref()
        .filter(|l| !l.is_empty())
        .map(|l| render_field("Location", &format!("<code>{}</code>", escape_html(l))))
        .unwrap_or_default();

    let description = render_field("Description", &paragraphs(&finding.description));
    let recommendation = render_field("Recommendation", &paragraphs(&finding.recommendation));

    let cwe = finding.cwe.as_deref().map(|id| {
        let trimmed = id.trim();
        let url = cwe_link(trimmed, DEFAULT_CWE_URL_TEMPLATE);
        render_field(
            "CWE",
            &format!(
                r#"<a href="{}" target="_blank" rel="noopener noreferrer">{}</a>"#,
                escape_html(&url),
                escape_html(trimmed)
            ),
        )
    });

    let secondary_cwe = if finding.secondary_cwe.is_empty() {
        None
    } else {
        let links: Vec<String> = finding
            .secondary_cwe
            .iter()
            .map(|id| {
                let trimmed = id.trim();
                let url = cwe_link(trimmed, DEFAULT_CWE_URL_TEMPLATE);
                format!(
                    r#"<a href="{}" target="_blank" rel="noopener noreferrer">{}</a>"#,
                    escape_html(&url),
                    escape_html(trimmed)
                )
            })
            .collect();
        Some(render_field("Secondary CWE", &links.join(", ")))
    };

    let cvss = match (finding.cvss_score, finding.cvss_vector.as_deref()) {
        (Some(score), Some(vector)) => Some(render_field(
            "CVSS",
            &format!(
                "<span class=\"cvss-score\">{:.1}</span> <span class=\"cvss-rating\">{}</span> <span class=\"cvss-vector\">{}</span>",
                score,
                escape_html(crate::state::cvss::rating(score)),
                escape_html(vector)
            ),
        )),
        _ => None,
    };

    let owasp = finding.owasp.as_deref().filter(|o| !o.is_empty()).map(|o| {
        render_field(
            "OWASP",
            &format!("<span class=\"tag\">{}</span>", escape_html(o)),
        )
    });

    let corroboration = if finding.corroborated_by.is_empty() {
        None
    } else {
        let tags: Vec<String> = finding
            .corroborated_by
            .iter()
            .map(|s| {
                format!(
                    "<span class=\"tag corroboration-tag\">{}</span>",
                    escape_html(s)
                )
            })
            .collect();
        Some(render_field("Corroborated by", &tags.join(" ")))
    };

    let screening = match (finding.screening, finding.confidence) {
        (Some(verdict), Some(confidence)) => Some(format!(
            r#"<div class="screening-badge screening-{}">{} <span class="confidence">({}% confidence)</span></div>"#,
            screening_css_class(verdict),
            escape_html(&verdict.to_string()),
            confidence
        )),
        (Some(verdict), None) => Some(format!(
            r#"<div class="screening-badge screening-{}">{}</div>"#,
            screening_css_class(verdict),
            escape_html(&verdict.to_string())
        )),
        _ => None,
    };

    let details = [
        location,
        cwe.unwrap_or_default(),
        secondary_cwe.unwrap_or_default(),
        cvss.unwrap_or_default(),
        owasp.unwrap_or_default(),
        corroboration.unwrap_or_default(),
        description,
        recommendation,
    ]
    .concat();

    format!(
        r#"<article class="finding-card {severity_class}">
  <div class="card-header">
    <div class="card-title-row">
      <span class="severity-badge">{severity_label}</span>
      <h2>{title}</h2>
    </div>
    <div class="card-subtitle">
      <span class="scanner-badge">{scanner}</span>
      {screening}
    </div>
  </div>
  <div class="card-body">
    {details}
  </div>
</article>"#,
        screening = screening.unwrap_or_default()
    )
}

fn render_field(label: &str, value_html: &str) -> String {
    format!(
        r#"<div class="field">
  <div class="field-label">{}</div>
  <div class="field-value">{}</div>
</div>"#,
        escape_html(label),
        value_html
    )
}

/// Convert plain text with line breaks into `<p>` paragraphs, escaping first.
fn paragraphs(text: &str) -> String {
    text.split('\n')
        .filter(|line| !line.is_empty())
        .map(|line| format!("<p>{}</p>", escape_html(line)))
        .collect::<String>()
}

fn severity_css_class(severity: Severity) -> &'static str {
    match severity {
        Severity::Critical => "severity-critical",
        Severity::High => "severity-high",
        Severity::Medium => "severity-medium",
        Severity::Low => "severity-low",
        Severity::Info => "severity-info",
    }
}

fn screening_css_class(screening: Screening) -> &'static str {
    match screening {
        Screening::Confirmed => "confirmed",
        Screening::Disputed => "disputed",
        Screening::Unclear => "unclear",
    }
}

/// Escape a value so it is safe to embed in HTML text or attribute contexts.
fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(ch),
        }
    }
    out
}

const CSS: &str = r#"
:root {
  --bg: #0b0f19;
  --surface: #111827;
  --surface-2: #1f2937;
  --text: #f3f4f6;
  --text-muted: #9ca3af;
  --border: #374151;
  --accent: #6366f1;
  --critical: #ef4444;
  --high: #f97316;
  --medium: #eab308;
  --low: #3b82f6;
  --info: #6b7280;
  --confirmed: #10b981;
  --disputed: #f43f5e;
  --unclear: #f59e0b;
  --radius: 12px;
  --shadow: 0 10px 30px rgba(0, 0, 0, 0.35);
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 0;
  background: var(--bg);
  color: var(--text);
  font-family: "Space Grotesk", "DM Sans", "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

.exec-header {
  max-width: 1100px;
  margin: 0 auto;
  padding: 48px 24px 32px;
}

.brand {
  font-size: 0.85rem;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--accent);
  margin-bottom: 8px;
}

.exec-header h1 {
  font-size: clamp(2rem, 5vw, 3rem);
  font-weight: 700;
  margin: 0 0 24px 0;
  line-height: 1.1;
}

.meta-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 12px 24px;
  margin-bottom: 32px;
}

.meta-item {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.meta-label {
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--text-muted);
  font-weight: 600;
}

.meta-value {
  font-size: 0.95rem;
  color: var(--text);
  word-break: break-word;
}

.severity-summary {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
  gap: 12px;
  margin-top: 24px;
}

.severity-card,
.total-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 18px 16px;
  text-align: center;
  box-shadow: var(--shadow);
}

.severity-card {
  border-top: 4px solid var(--info);
}

.severity-card.critical { border-top-color: var(--critical); }
.severity-card.high { border-top-color: var(--high); }
.severity-card.medium { border-top-color: var(--medium); }
.severity-card.low { border-top-color: var(--low); }
.severity-card.info { border-top-color: var(--info); }

.severity-count {
  display: block;
  font-size: 2rem;
  font-weight: 700;
  line-height: 1;
  margin-bottom: 6px;
}

.severity-label {
  font-size: 0.8rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--text-muted);
  font-weight: 600;
}

.total-card {
  border-top-color: var(--accent);
}

.findings {
  max-width: 1100px;
  margin: 0 auto;
  padding: 0 24px 48px;
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.finding-card {
  background: var(--surface);
  border: 1px solid var(--border);
  border-left: 6px solid var(--info);
  border-radius: var(--radius);
  overflow: hidden;
  box-shadow: var(--shadow);
}

.finding-card.severity-critical { border-left-color: var(--critical); }
.finding-card.severity-high { border-left-color: var(--high); }
.finding-card.severity-medium { border-left-color: var(--medium); }
.finding-card.severity-low { border-left-color: var(--low); }
.finding-card.severity-info { border-left-color: var(--info); }

.card-header {
  background: var(--surface-2);
  padding: 20px 24px;
  border-bottom: 1px solid var(--border);
}

.card-title-row {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}

.card-title-row h2 {
  margin: 0;
  font-size: 1.35rem;
  font-weight: 600;
  line-height: 1.2;
}

.severity-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 4px 10px;
  border-radius: 999px;
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  background: var(--info);
  color: #fff;
}

.severity-critical .severity-badge { background: var(--critical); }
.severity-high .severity-badge { background: var(--high); }
.severity-medium .severity-badge { background: var(--medium); color: #1f2937; }
.severity-low .severity-badge { background: var(--low); }

.card-subtitle {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 12px;
}

.scanner-badge {
  font-size: 0.8rem;
  color: var(--text-muted);
  font-weight: 500;
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.screening-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px;
  border-radius: 999px;
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  background: var(--surface);
  border: 1px solid var(--border);
}

.screening-badge.confirmed { border-color: var(--confirmed); color: var(--confirmed); }
.screening-badge.disputed { border-color: var(--disputed); color: var(--disputed); }
.screening-badge.unclear { border-color: var(--unclear); color: var(--unclear); }

.screening-badge .confidence {
  opacity: 0.8;
  font-weight: 500;
  text-transform: none;
}

.card-body {
  padding: 20px 24px;
  display: grid;
  grid-template-columns: 1fr;
  gap: 18px;
}

.field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.field-label {
  font-size: 0.7rem;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--text-muted);
  font-weight: 700;
}

.field-value {
  font-size: 0.95rem;
  color: var(--text);
}

.field-value p {
  margin: 0 0 10px 0;
}

.field-value p:last-child {
  margin-bottom: 0;
}

.field-value code {
  background: rgba(99, 102, 241, 0.12);
  color: #c7d2fe;
  padding: 2px 6px;
  border-radius: 4px;
  font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace;
  font-size: 0.85em;
}

.field-value a {
  color: var(--accent);
  text-decoration: none;
  border-bottom: 1px solid transparent;
}

.field-value a:hover {
  border-bottom-color: var(--accent);
}

.tag {
  display: inline-block;
  padding: 3px 8px;
  border-radius: 6px;
  font-size: 0.75rem;
  font-weight: 600;
  background: var(--surface-2);
  border: 1px solid var(--border);
  color: var(--text);
  margin: 0 4px 4px 0;
}

.corroboration-tag {
  background: rgba(16, 185, 129, 0.1);
  border-color: rgba(16, 185, 129, 0.35);
  color: #6ee7b7;
}

.cvss-score {
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--text);
}

.cvss-rating {
  font-weight: 600;
  color: var(--text-muted);
}

.cvss-vector {
  font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace;
  font-size: 0.85em;
  color: var(--text-muted);
}

.empty-state {
  max-width: 1100px;
  margin: 0 auto;
  padding: 64px 24px;
  text-align: center;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}

.empty-icon {
  width: 64px;
  height: 64px;
  margin: 0 auto 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: rgba(16, 185, 129, 0.12);
  color: #6ee7b7;
  font-size: 1.75rem;
  font-weight: 700;
}

.empty-state h2 {
  margin: 0 0 8px 0;
  font-size: 1.5rem;
}

.empty-state p {
  margin: 0;
  color: var(--text-muted);
}

.report-footer {
  max-width: 1100px;
  margin: 0 auto;
  padding: 24px;
  text-align: center;
  font-size: 0.8rem;
  color: var(--text-muted);
  border-top: 1px solid var(--border);
}

@media print {
  :root {
    --bg: #ffffff;
    --surface: #ffffff;
    --surface-2: #f9fafb;
    --text: #111827;
    --text-muted: #4b5563;
    --border: #d1d5db;
    --accent: #4f46e5;
    --critical: #dc2626;
    --high: #ea580c;
    --medium: #ca8a04;
    --low: #2563eb;
    --info: #4b5563;
    --confirmed: #059669;
    --disputed: #e11d48;
    --unclear: #d97706;
    --shadow: none;
  }

  body {
    background: #fff;
    color: #111;
    font-size: 11pt;
  }

  .exec-header,
  .findings,
  .report-footer {
    max-width: none;
    padding-left: 0;
    padding-right: 0;
  }

  .finding-card {
    box-shadow: none;
    break-inside: avoid;
    page-break-inside: avoid;
  }

  .severity-card,
  .total-card {
    box-shadow: none;
  }

  a {
    color: #111 !important;
    text-decoration: underline !important;
  }

  .field-value code {
    background: #f3f4f6;
    color: #111;
  }

  .screening-badge.confirmed,
  .screening-badge.disputed,
  .screening-badge.unclear {
    border: 1px solid var(--border);
    color: var(--text);
  }

  .corroboration-tag {
    background: #f3f4f6;
    color: #111;
    border-color: var(--border);
  }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::finding::{Finding, Screening, Severity};

    fn sample_finding() -> Finding {
        Finding {
            scanner: "sast".to_string(),
            severity: Severity::High,
            title: "SQL Injection".to_string(),
            description: "User input concatenated into query.\nSecond line.".to_string(),
            location: Some("src/db.rs:42".to_string()),
            recommendation: "Use parameterized queries".to_string(),
            corroborated_by: vec!["supply-chain".to_string()],
            cwe: Some("CWE-89".to_string()),
            secondary_cwe: vec!["CWE-20".to_string()],
            cvss_vector: Some("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H".to_string()),
            cvss_score: Some(9.8),
            owasp: Some("A03:2021-Injection".to_string()),
            confidence: Some(85),
            screening: Some(Screening::Confirmed),
            evidence: None,
        }
    }

    #[test]
    fn empty_findings_render_valid_html() {
        let html = render_findings_html(&[]);
        assert!(html.starts_with("<!DOCTYPE html>"));
        assert!(html.contains("No findings detected"));
        assert!(html.contains("Total findings"));
    }

    #[test]
    fn rendering_is_deterministic() {
        let findings = vec![sample_finding()];
        let a = render_findings_html(&findings);
        let b = render_findings_html(&findings);
        assert_eq!(a, b, "same findings must produce byte-identical HTML");
    }

    #[test]
    fn untrusted_fields_are_escaped() {
        let mut f = sample_finding();
        f.title = "<img src=x onerror=alert(1)>".to_string();
        f.description = "<script>alert(1)</script>".to_string();
        f.location = Some("src/<foo>.rs:1".to_string());
        f.scanner = "scanner&co".to_string();
        f.cwe = Some("CWE-89\"".to_string());
        f.owasp = Some("A01'x".to_string());

        let html = render_findings_html(&[f]);
        assert!(!html.contains("<img src=x onerror=alert(1)>"));
        assert!(html.contains("&lt;img src=x onerror=alert(1)&gt;"));
        assert!(!html.contains("<script>alert(1)</script>"));
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(!html.contains("src/<foo>.rs:1"));
        assert!(html.contains("src/&lt;foo&gt;.rs:1"));
        assert!(!html.contains("scanner&co"));
        assert!(html.contains("scanner&amp;co"));
        assert!(!html.contains("CWE-89\""));
        assert!(html.contains("CWE-89&quot;"));
        assert!(html.contains("A01&#39;x"));
    }

    #[test]
    fn severity_summary_counts_are_correct() {
        let html = render_findings_html(&[sample_finding()]);
        assert!(html.contains(r#"<span class="severity-label">Total findings</span>"#));
        assert!(html.contains(r#"<div class="severity-card high">"#));
        assert!(html.contains(r#"<span class="severity-label">High</span>"#));
        assert!(html.contains(r#"<span class="severity-count">1</span>"#));
    }

    #[test]
    fn enriched_finding_renders_fields() {
        let html = render_findings_html(&[sample_finding()]);
        assert!(html.contains("SQL Injection"));
        assert!(html.contains("src/db.rs:42"));
        assert!(html.contains("User input concatenated into query."));
        assert!(html.contains("Use parameterized queries"));
        assert!(html.contains("CWE-89"));
        assert!(html.contains("CWE-20"));
        assert!(html.contains("9.8"));
        assert!(html.contains("A03:2021-Injection"));
        assert!(html.contains("supply-chain"));
        assert!(html.contains("confirmed"));
        assert!(html.contains("85% confidence"));
    }

    #[test]
    fn cwe_link_points_at_default_template() {
        let html = render_findings_html(&[sample_finding()]);
        assert!(html.contains("https://cwe.mitre.org/data/definitions/89.html"));
        assert!(html.contains("https://cwe.mitre.org/data/definitions/20.html"));
    }

    #[test]
    fn report_meta_lines_are_escaped() {
        let html = render_report_html(
            &[],
            "Title<script>",
            &[("Key<img>", "Value&"), ("Branch", "feat/<x>")],
        );
        assert!(html.contains("Title&lt;script&gt;"));
        assert!(html.contains("Key&lt;img&gt;"));
        assert!(html.contains("Value&amp;"));
        assert!(html.contains("feat/&lt;x&gt;"));
    }

    #[test]
    fn findings_sorted_by_severity_then_location_then_title() {
        let b = Finding {
            scanner: "b".to_string(),
            severity: Severity::Critical,
            title: "B".to_string(),
            description: "d".to_string(),
            location: Some("src/b.rs:1".to_string()),
            recommendation: "r".to_string(),
            ..sample_finding()
        };
        let a = Finding {
            scanner: "a".to_string(),
            severity: Severity::Critical,
            title: "A".to_string(),
            description: "d".to_string(),
            location: Some("src/a.rs:1".to_string()),
            recommendation: "r".to_string(),
            ..sample_finding()
        };
        let html = render_findings_html(&[b.clone(), a.clone()]);
        let a_pos = html.find("<h2>A</h2>").unwrap();
        let b_pos = html.find("<h2>B</h2>").unwrap();
        assert!(a_pos < b_pos, "A must appear before B");
    }
}
