use std::collections::HashMap;
use std::time::Duration;

use anyhow::{anyhow, Result};
use reqwest::Client;
use serde::Deserialize;

use super::{severity_counts, CiContext, CiPlatformKind};
use crate::state::{Finding, Severity};

pub const STICKY_COMMENT_MARKER: &str = "<!-- zentra-ci-comment -->";

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CiCommentPlan {
    Publish { body: String },
    Skip { reason: String },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum StickyCommentAction {
    Create { body: String },
    Update { id: u64, body: String },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GitlabAuthHeader {
    pub name: &'static str,
    pub value: String,
}

#[derive(Deserialize)]
struct ExistingComment {
    id: u64,
    body: String,
}

pub fn select_sticky_comment_action(
    existing_comments: &[(u64, String)],
    body: String,
) -> StickyCommentAction {
    existing_comments
        .iter()
        .find(|(_, existing_body)| existing_body.contains(STICKY_COMMENT_MARKER))
        .map(|(id, _)| StickyCommentAction::Update {
            id: *id,
            body: body.clone(),
        })
        .unwrap_or(StickyCommentAction::Create { body })
}

pub fn prepare_comment_request_from_env(
    env: &HashMap<String, String>,
    context: &CiContext,
    findings: &[Finding],
) -> CiCommentPlan {
    if comment_token(env, context.platform).is_none() {
        return CiCommentPlan::Skip {
            reason: "CI comment skipped: no platform token available".to_string(),
        };
    }

    if context.pr_or_mr_number.is_none() {
        return CiCommentPlan::Skip {
            reason: "CI comment skipped: missing PR/MR number".to_string(),
        };
    }

    match context.platform {
        CiPlatformKind::Github if env.get("GITHUB_REPOSITORY").is_none() => {
            return CiCommentPlan::Skip {
                reason: "CI comment skipped: missing GITHUB_REPOSITORY".to_string(),
            };
        }
        CiPlatformKind::Gitlab if env.get("CI_PROJECT_ID").is_none() => {
            return CiCommentPlan::Skip {
                reason: "CI comment skipped: missing CI_PROJECT_ID".to_string(),
            };
        }
        _ => {}
    }

    CiCommentPlan::Publish {
        body: build_sticky_comment_body(context, findings),
    }
}

pub fn build_sticky_comment_body(context: &CiContext, findings: &[Finding]) -> String {
    let counts = severity_counts(findings);
    let (status_label, status_note) = if counts.critical > 0 {
        (
            "❌ Failed",
            format!(
                "**Fix {} Critical finding{} before you merge this.**",
                counts.critical,
                if counts.critical == 1 { "" } else { "s" }
            ),
        )
    } else {
        (
            "✅ Passed",
            "No Critical findings in the scanned changes.".to_string(),
        )
    };

    let scope = context.pr_or_mr_number.as_deref().unwrap_or("unknown");
    let commit_suffix = context
        .commit_sha
        .as_deref()
        .map(|sha| format!(" · `{}`", short_sha(sha)))
        .unwrap_or_default();

    let mut body = format!(
        "{STICKY_COMMENT_MARKER}\n\
## 🛡️ Zentra Security Scan — {status_label}\n\n\
{status_note}\n\n\
| | |\n\
|---|---|\n\
| **Platform** | {platform} |\n\
| **Scope** | PR/MR #{scope} |\n\
| **Base → Head** | `{base}` → `{head}` |\n\n\
### Findings ({total} total — 🔴 {critical} Critical · 🟠 {high} High · 🟡 {medium} Medium · 🔵 {low} Low · ⚪ {info} Info)\n\n",
        platform = context.platform.as_str(),
        base = context.base_ref,
        head = context.head_ref,
        total = findings.len(),
        critical = counts.critical,
        high = counts.high,
        medium = counts.medium,
        low = counts.low,
        info = counts.info,
    );

    if findings.is_empty() {
        body.push_str("No findings.\n");
    } else {
        body.push_str("| Severity | Finding | Location | CWE |\n|---|---|---|---|\n");
        let mut sorted_findings = findings.iter().collect::<Vec<_>>();
        sorted_findings.sort_by_key(|finding| finding.severity.order());
        for finding in sorted_findings {
            body.push_str(&format!(
                "| {} {} | {} | `{}` | {} |\n",
                severity_emoji(&finding.severity),
                finding.severity,
                finding.title,
                finding.location.as_deref().unwrap_or("N/A"),
                finding.cwe.as_deref().unwrap_or("—"),
            ));
        }
    }

    body.push_str(&format!(
        "\n<details>\n<summary>📄 Scan artifacts</summary>\n\n\
- `.zentra/ci-report.md`\n\
- `.zentra/ci-report.json`\n\n\
</details>\n\n\
<sub>Generated by Zentra CI{commit_suffix} · Fail threshold: Critical</sub>\n"
    ));

    body
}

/// First 7 characters of a commit SHA, truncated on a char boundary. `commit_sha`
/// comes verbatim from `GITHUB_SHA` / `CI_COMMIT_SHA`; a byte slice `&sha[..7]`
/// panics when a multibyte value puts byte 7 mid-character (same bug class as the
/// F19 sibling truncations in mode.rs / scan_ui.rs).
fn short_sha(sha: &str) -> &str {
    let end = sha
        .char_indices()
        .nth(7)
        .map(|(i, _)| i)
        .unwrap_or(sha.len());
    &sha[..end]
}

fn severity_emoji(severity: &Severity) -> &'static str {
    match severity {
        Severity::Critical => "🔴",
        Severity::High => "🟠",
        Severity::Medium => "🟡",
        Severity::Low => "🔵",
        Severity::Info => "⚪",
    }
}

pub fn redact_token(token: &str) -> String {
    if token.is_empty() {
        String::new()
    } else {
        "[redacted]".to_string()
    }
}

pub fn comment_http_timeout() -> Duration {
    Duration::from_secs(10)
}

fn comment_http_client() -> Result<Client> {
    Ok(Client::builder().timeout(comment_http_timeout()).build()?)
}

pub fn gitlab_auth_header_from_env(env: &HashMap<String, String>) -> Option<GitlabAuthHeader> {
    env.get("GITLAB_TOKEN")
        .filter(|value| !value.is_empty())
        .map(|token| GitlabAuthHeader {
            name: "Authorization",
            value: format!("Bearer {token}"),
        })
        .or_else(|| {
            env.get("CI_JOB_TOKEN")
                .filter(|value| !value.is_empty())
                .map(|token| GitlabAuthHeader {
                    name: "JOB-TOKEN",
                    value: token.to_string(),
                })
        })
}

pub async fn publish_comment_best_effort(context: &CiContext, findings: &[Finding]) -> Result<()> {
    let env = std::env::vars().collect::<HashMap<_, _>>();
    match prepare_comment_request_from_env(&env, context, findings) {
        CiCommentPlan::Skip { reason } => {
            println!("{reason}");
            Ok(())
        }
        CiCommentPlan::Publish { body } => publish_comment(&env, context, &body).await,
    }
}

/// GET and parse the existing-comments list under a hard memory bound. The API
/// host comes from `GITHUB_API_URL` / `CI_API_V4_URL` (env), so a misconfigured
/// or MITM'd endpoint must not be able to OOM the runner via an unbounded body —
/// reqwest's `.json()` buffers the whole body first. 8 MiB is far above any real
/// comment list; an over-cap body is truncated and fails to parse (comment
/// publishing is best-effort, so that degrades cleanly).
async fn fetch_existing_comments(req: reqwest::RequestBuilder) -> Result<Vec<ExistingComment>> {
    const MAX_LIST_BYTES: usize = 8 * 1024 * 1024;
    let mut resp = req.send().await?.error_for_status()?;
    let mut buf: Vec<u8> = Vec::new();
    while buf.len() < MAX_LIST_BYTES {
        match resp.chunk().await? {
            Some(chunk) => {
                let take = (MAX_LIST_BYTES - buf.len()).min(chunk.len());
                buf.extend_from_slice(&chunk[..take]);
            }
            None => break,
        }
    }
    Ok(serde_json::from_slice(&buf)?)
}

async fn publish_comment(
    env: &HashMap<String, String>,
    context: &CiContext,
    body: &str,
) -> Result<()> {
    match context.platform {
        CiPlatformKind::Github => publish_github_comment(env, context, body).await,
        CiPlatformKind::Gitlab => publish_gitlab_comment(env, context, body).await,
    }
}

async fn publish_github_comment(
    env: &HashMap<String, String>,
    context: &CiContext,
    body: &str,
) -> Result<()> {
    let token = comment_token(env, context.platform).ok_or_else(|| anyhow!("missing token"))?;
    let repo = env
        .get("GITHUB_REPOSITORY")
        .ok_or_else(|| anyhow!("missing GITHUB_REPOSITORY"))?;
    let pr = context
        .pr_or_mr_number
        .as_deref()
        .ok_or_else(|| anyhow!("missing PR number"))?;
    let api_url = env
        .get("GITHUB_API_URL")
        .map(String::as_str)
        .unwrap_or("https://api.github.com");
    let url = format!("{api_url}/repos/{repo}/issues/{pr}/comments");

    let client = comment_http_client()?;
    let existing = fetch_existing_comments(
        client
            .get(&url)
            .bearer_auth(token)
            .header("User-Agent", "zentra-cli"),
    )
    .await?
    .into_iter()
    .map(|comment| (comment.id, comment.body))
    .collect::<Vec<_>>();

    match select_sticky_comment_action(&existing, body.to_string()) {
        StickyCommentAction::Create { body } => {
            client
                .post(url)
                .bearer_auth(token)
                .header("User-Agent", "zentra-cli")
                .json(&serde_json::json!({ "body": body }))
                .send()
                .await?
                .error_for_status()?;
        }
        StickyCommentAction::Update { id, body } => {
            let update_url = format!("{api_url}/repos/{repo}/issues/comments/{id}");
            client
                .patch(update_url)
                .bearer_auth(token)
                .header("User-Agent", "zentra-cli")
                .json(&serde_json::json!({ "body": body }))
                .send()
                .await?
                .error_for_status()?;
        }
    }
    Ok(())
}

async fn publish_gitlab_comment(
    env: &HashMap<String, String>,
    context: &CiContext,
    body: &str,
) -> Result<()> {
    let auth_header = gitlab_auth_header_from_env(env).ok_or_else(|| anyhow!("missing token"))?;
    let project_id = env
        .get("CI_PROJECT_ID")
        .ok_or_else(|| anyhow!("missing CI_PROJECT_ID"))?;
    let mr = context
        .pr_or_mr_number
        .as_deref()
        .ok_or_else(|| anyhow!("missing MR number"))?;
    let api_url = env
        .get("CI_API_V4_URL")
        .map(String::as_str)
        .unwrap_or("https://gitlab.com/api/v4");
    let url = format!("{api_url}/projects/{project_id}/merge_requests/{mr}/notes");

    let client = comment_http_client()?;
    let existing = fetch_existing_comments(
        client
            .get(&url)
            .header(auth_header.name, auth_header.value.clone()),
    )
    .await?
    .into_iter()
    .map(|comment| (comment.id, comment.body))
    .collect::<Vec<_>>();

    match select_sticky_comment_action(&existing, body.to_string()) {
        StickyCommentAction::Create { body } => {
            client
                .post(url)
                .header(auth_header.name, auth_header.value.clone())
                .json(&serde_json::json!({ "body": body }))
                .send()
                .await?
                .error_for_status()?;
        }
        StickyCommentAction::Update { id, body } => {
            let update_url =
                format!("{api_url}/projects/{project_id}/merge_requests/{mr}/notes/{id}");
            client
                .put(update_url)
                .header(auth_header.name, auth_header.value.clone())
                .json(&serde_json::json!({ "body": body }))
                .send()
                .await?
                .error_for_status()?;
        }
    }
    Ok(())
}

fn comment_token(env: &HashMap<String, String>, platform: CiPlatformKind) -> Option<&str> {
    let names: &[&str] = match platform {
        CiPlatformKind::Github => &["GITHUB_TOKEN", "GH_TOKEN"],
        CiPlatformKind::Gitlab => &["GITLAB_TOKEN", "CI_JOB_TOKEN"],
    };

    names.iter().find_map(|name| {
        env.get(*name)
            .filter(|value| !value.is_empty())
            .map(String::as_str)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // L6 (chaos re-test): commit_sha is verbatim from GITHUB_SHA / CI_COMMIT_SHA.
    // A byte slice `&sha[..7]` panics on a multibyte value; short_sha truncates on
    // a char boundary instead.
    #[test]
    fn short_sha_handles_multibyte_without_panicking() {
        // 7 Cyrillic chars = 14 bytes; byte 7 is mid-character.
        let s = "ааааааа";
        let got = short_sha(s);
        assert!(s.starts_with(got));
        assert!(got.chars().count() <= 7);
        // ASCII SHA truncates to 7 chars as before.
        assert_eq!(short_sha("0123456789abcdef"), "0123456");
        // Shorter-than-7 returns the whole string.
        assert_eq!(short_sha("abc"), "abc");
    }

    // L3 (chaos re-test): the existing-comments GET buffered the whole response
    // with `.json()`. fetch_existing_comments caps the read; an over-cap body is
    // truncated and fails to parse rather than exhausting memory.
    #[tokio::test]
    async fn fetch_existing_comments_parses_small_list() {
        let server = wiremock::MockServer::start().await;
        wiremock::Mock::given(wiremock::matchers::method("GET"))
            .and(wiremock::matchers::path("/comments"))
            .respond_with(
                wiremock::ResponseTemplate::new(200)
                    .set_body_string(r#"[{"id":1,"body":"hello"},{"id":2,"body":"world"}]"#),
            )
            .mount(&server)
            .await;
        let client = comment_http_client().unwrap();
        let got = fetch_existing_comments(client.get(format!("{}/comments", server.uri())))
            .await
            .unwrap();
        assert_eq!(got.len(), 2);
        assert_eq!(got[0].id, 1);
        assert_eq!(got[1].body, "world");
    }
}
